### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Mitmischer** [pafnow/vrt-graphml-for-yed#1]
Hello,

thank you for the great item set! I was confused as to how to import the symbols, so maybe you should add some documentation in the README. Here is my workflow, I don't know if that is "the way it should be done":

1. Open a .graphml-file
2. Open Palette Manager
3. Click New Section
4. Choose Adopt from Document
5. Choose an appropriate name

**Comment by itthing** [comment]
Tried doing #1 above, but I'm getting 
y.H.B.B.a: SAX error: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
	at com.yworks.A.B.G.A.U$H.ā(Unknown Source)
	at com.yworks.A.B.G.A.U.ā(Unknown Source)
	at com.yworks.A.B.G.A.Q.ā(Unknown Source)
	at y.H.G.ā(Unknown Source)
	at y.B.A.M.Đ(Unknown Source)
	at y.B.d.č(Unknown Source)
	at y.B.d.ā(Unknown Source)
	at y.B.d.ă(Unknown Source)
	at com.yworks.A.B.W.ă(Unknown Source)
	at com.yworks.A.B.W.ā(Unknown Source)
	at com.yworks.A.J.P.ā(Unknown Source)
	at com.yworks.A.J.P.ā(Unknown Source)
	at com.yworks.A.J.P$A.Ă(Unknown Source)
	at com.yworks.A.J.P.ā(Unknown Source)
	at com.yworks.A.K.D.ā(Unknown Source)
	at com.yworks.A.K.j.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at com.jidesoft.plaf.basic.BasicJideButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 44; columnNumber: 91; Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at com.yworks.A.B.G.A.H.ā(Unknown Source)
	at com.yworks.A.B.G.A.H.ā(Unknown Source)
	... 54 more

**Comment by pafnow** [comment]
done, thanks
